### ISSUE TITLE
Full file examples

### ISSUE THREAD

**Issue by fpolli** [adonisjs/v6-docs#42]
Hi,

The problem I have with the documentation, and it is by no means unique to Adonis but rather the norm, is the lack of full file examples. Like, with service providers, there are all these snippets of doing a binding, or a register, but nothing to show us what an entire provider file looks like. A link or a screenshot at the bottom with "Tying It All Together" would be very helpful.

**Comment by RomainLanz** [comment]
Hey @fpolli! 👋🏻 

Because it all depends on what your provider is doing.
It may be only a few lines of code (like the example), or it could be a bit bigger.

Would add links to real providers (for example, each official package) would feel to be a great addition to you?

For example, that is the mail one: https://github.com/adonisjs/mail/blob/develop/providers/mail_provider.ts

**Comment by fpolli** [comment]
@RomainLanz That link was unbelievably helpful. I learned so much by being able to see a full-featured example in action. I've tried looking up some providers but a lot of them don't do much. Seeing one that does pretty much everything helps enormously. Answered a lot of questions. Thank you
