### ISSUE TITLE
Installation error with yarn

### ISSUE THREAD

**Issue by Raesta** [adonisjs/v6-docs#73]
Hey,

I have already talked about this privately with @Julien-R44, so here is the issue I encountered while following the documentation.

During installation via the command `yarn create adonisjs@latest hello-world`, I encountered an error.

![image](https://github.com/adonisjs/v6-docs/assets/4834347/eb8bf195-784a-4925-aa11-8d7f2e63c9a5)

This error is because the keyword `latest` does not exist since Yarn by default takes the latest version.

You can specify a version, of course, but not use this keyword.

PR to fix the "problem" : https://github.com/adonisjs/v6-docs/pull/74

**Comment by Julien-R44** [comment]
I think there are a few things to make sure of : 

- here you're using yarn 1. i wouldn't say it's deprecated ( ? ) but it's very old. and indeed if you remove the `@latest` it works
- with the latest versions of yarn (4) `yarn create adonisjs@latest` works correctly

So we should make sure that `yarn create adonisjs` with Yarn 4 uses the latest version of `create-adonisjs`. But I think it will not.

Otherwise, if a guy is using Yarn 4 and we recommend to use `yarn create adonisjs` without the `@latest`, he will probably download an older version of `create-adonisjs`

Or, rather than bother. Just indicate in the documentation that only Yarn 4 is supported. I would say this is probably our better option, as there is always a lot of trouble with Yarn Classic

**Comment by Raesta** [comment]
For more context, i use OSX & install with brew : https://formulae.brew.sh/formula/yarn

But use 1.x version of yarn :-(

**Comment by Julien-R44** [comment]
@RomainLanz any opinions? since you know Yarn way better than me

**Comment by RomainLanz** [comment]
IMO, we should remove any mention of `yarn` or `pnpm`, if people want to use something else than what is the default in Node.js, they should know how their tool work.

**Comment by thetutlage** [comment]
I agree with @RomainLanz here. Making different package managers work is outside of our scope. So, let's keep docs for just npm.

**Comment by Raesta** [comment]
@RomainLanz @thetutlage All right, I've made the changes to follow your point.

**Comment by thetutlage** [comment]
Yes, we should

**Comment by Raesta** [comment]
@thetutlage I have made modifications throughout the entire documentation.
